# Generated by Django 3.1.6 on 2021-07-02 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210614_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stars',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
